H: 480
W: 640
color_K_path: intrinsic/intrinsic_color.txt
color_path: color
color_post: .jpg
combined_obj_dist_thd: 200
connected_thd: 3600
depth_factor: 1000
depth_path: depth
depth_post: .png
desc_type: 2
inv_overlap_pyramid_ratio: 8
label_list_area_thd: 400
leave_multi_obj_match: 0
obj_desc_match_thd: 0.5
out_path: /opt/data/private/SGAM/demo/demo_sgam_res
output_patch_size: 256
overlap_desc_dist_thd: 0.25
overlap_radius: 128
pose_path: pose
pose_post: .txt
radius_thd_down: 100
radius_thd_up: 128
root_path: /opt/data/private/SGAM/demo/demo_data/ScanData
same_overlap_dist: 100
sem_path: label-filt
sem_path_SEEM: /data2/zys/SEEMRes
sem_post: .png
sem_post_SEEM: .png
semantic_mode: ScanNetGT
small_label_filted_thd_inside_area: 900
small_label_filted_thd_on_bound: 20
