adaptive_size_thd: 0.6
alpha_list:
- 5.0
area_from_size_H: 480
area_from_size_W: 640
color_K_path: intrinsic/intrinsic_color.txt
color_path: color
color_post: .jpg
crop_from_size_H: 968
crop_from_size_W: 1296
crop_size_H: 480
crop_size_W: 640
depth_factor: 1000
depth_path: depth
depth_post: .png
draw_adap: 0
eval_from_size_H: 480
eval_from_size_W: 640
filter_area_num: 1
inlier_thd_mode: 0
match_num: 500
out_path: /opt/data/private/SGAM/demo/demo_sgam_res
pose_path: pose
pose_post: .txt
rejection_mode: 1
root_path: /opt/data/private/SGAM/demo/demo_data/ScanData
sem_path: label-filt
sem_post: .png
standard_area_size: 256
